### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#188]
isoline on top of a boxfil

**Comment by James-Crean** [comment]
@doutriaux1, @scottwittenburg 
Isoline seems to be broken in the current build of vcdat/vcs-js/vcs.  

Here is a stack trace when trying to plot any clt.nc variable as an isoline.

---
```
"Traceback (most recent call last):
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/wslink/websocket.py", line 274, in onMessage
    results = func(obj, *args, **kwargs)
  File "build/bdist.macosx-10.9-x86_64/egg/vcs_server/Visualizer.py", line 56, in plot
    plot.loadVariable(all_vars)
  File "build/bdist.macosx-10.9-x86_64/egg/vcs_server/VcsPlot.py", line 114, in loadVariable
    self._plot.variables = var
  File "build/bdist.macosx-10.9-x86_64/egg/vcs_server/PlotManager.py", line 43, in set_vars
    self.plot()
  File "build/bdist.macosx-10.9-x86_64/egg/vcs_server/PlotManager.py", line 95, in plot
    self.dp = self.canvas.plot(*args, ratio="autot")
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/vcs/Canvas.py", line 2775, in plot
    a = self.__plot(arglist, keyargs)
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/vcs/Canvas.py", line 4119, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/vcs/VTKPlots.py", line 682, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 309, in plot
    self._updateContourLevelsAndColors()
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/vcs/vcsvtk/isolinepipeline.py", line 29, in _updateContourLevelsAndColors
    if numpy.allclose(self._contourLevels[0], [0., 1.e20]) or \
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/numpy/core/numeric.py", line 2459, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/Users/crean2/anaconda2/envs/nightly/lib/python2.7/site-packages/numpy/core/numeric.py", line 2538, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
"
```

**Comment by scottwittenburg** [comment]
Hi @James-Crean, I just installed the current vcs master and ran the `tests/test_vcs_isoline_width_stipple.py` which seemed to work fine.  Can you share a Javascript snippet I could use to try and reproduce that on the `vcs-js` side?  Thanks!

**Comment by James-Crean** [comment]
Added in #190.

An issue has been created for isoline in #195.
